/* 
**  mod_memc_sess.c -- Apache sample memc_sess module
**  [Autogenerated via ``apxs -n memc_sess -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i -l memcached mod_memc_sess.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /memc_sess in as follows:
**
**    #   apache2.conf
**    LoadModule memc_sess_module modules/mod_memc_sess.so
**    <Location /memc_sess>
**    SetHandler memc_sess
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /memc_sess and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/memc_sess 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_memc_sess.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "ap_config.h"
#include "ap_regex.h"
#include "apreq2/apreq_cookie.h"
#include "libmemcached/memcached.h"

#define ERR_MSG_HEAD "MemcSess: "
#define ERR_MSG_NO_MEMCACHED_HOST (ERR_MSG_HEAD "Memcached host is empty ")
#define ERR_MSG_NO_SESSION_KEY_NAME (ERR_MSG_HEAD "Session key name is empty ")
#define ERR_MSG_NO_SESSION_KEY_PREFIX (ERR_MSG_HEAD "Session key prefix is empty ")
#define ERR_MSG_NO_REDIRECT_URL   (ERR_MSG_HEAD "Redirect URL is empty ")

#define ERRLOG(...) ap_log_error(APLOG_MARK, APLOG_ERR, 0, NULL, __VA_ARGS__)

typedef struct {
  const char *memcached_host;
  const char *session_key_name;
  const char *session_key_prefix;
  const char *redirect_url;
} memc_sess_conf;

extern module AP_MODULE_DECLARE_DATA memc_sess_module;

static void *create_memc_sess_conf(apr_pool_t *p, server_rec *s)
{
  return apr_pcalloc(p, sizeof(memc_sess_conf));
}

static memc_sess_conf *conf_from_req(request_rec *r)
{
  return ap_get_module_config(r->server->module_config, &memc_sess_module);
}

static const char *get_memcached_host(request_rec *r)
{
  return conf_from_req(r)->memcached_host;
}

static const char *get_session_key_name(request_rec *r)
{
  return conf_from_req(r)->session_key_name;
}

static const char *get_session_key_prefix(request_rec *r)
{
  return conf_from_req(r)->session_key_prefix;
}

static const char *get_redirect_url(request_rec *r)
{
  return conf_from_req(r)->redirect_url;
}

static int memc_get_session(const char *memcached_host, 
                            const char *key, const int vlen, char *val)
{
  int flags;
  char *res;
  size_t reslen; 
  size_t klen = strlen(key);
  struct memcached_st *memc;
  struct memcached_server_st *servers;
  memcached_return rc;

  memc = memcached_create(NULL);
  servers = memcached_servers_parse((char *)memcached_host);
  rc = memcached_server_push(memc, servers);

  if(rc != MEMCACHED_SUCCESS) {
    ERRLOG((ERR_MSG_HEAD "memcached_server_push error. %s "),
           memcached_strerror(memc, rc));
    return 0;
  }

  res = memcached_get(memc, key, klen, &reslen, &flags, &rc);
  if(rc != MEMCACHED_SUCCESS) {
    ERRLOG((ERR_MSG_HEAD "memcached_get error. %s "),
           memcached_strerror(memc, rc));
    return 0;
  }
  strncpy(val, res, reslen > vlen ? vlen : reslen);

  memcached_server_list_free(servers);
  memcached_free(memc);

  return 1;
}

static const char *get_session_key(request_rec *r, const char *key_name)
{
  apr_status_t st;
  apr_table_t *cookie_jar;
  const char *cookie_string;
  const char *cookie_value;

  cookie_string = apr_table_get(r->headers_in, "Cookie");
  if (!cookie_string)
    return NULL;

  cookie_jar = apr_table_make(r->pool, 1);
  st = apreq_parse_cookie_header(r->pool, cookie_jar, cookie_string);
  if (st != APR_SUCCESS) {
    char buf[512];
    apreq_strerror(st, buf, sizeof(buf));
    ERRLOG((ERR_MSG_HEAD "apreq_parse_cookie_header error. %s "), buf);
    return NULL;
  }

  cookie_value = apr_table_get(cookie_jar, key_name);
  if (!cookie_value)
    return NULL;

  return cookie_value;
}

static int memc_sess_handler(request_rec *r)
{
  int rc;
  const char *memcached_host = get_memcached_host(r);
  const char *session_key_name = get_session_key_name(r);
  const char *session_key_prefix = get_session_key_prefix(r);
  const char *redirect_url = get_redirect_url(r);
  const char *session_key;
  char session_key_buf[256];
  char buf[1024];

  if (!memcached_host) {
    ERRLOG(ERR_MSG_NO_MEMCACHED_HOST);
    return HTTP_INTERNAL_SERVER_ERROR;
  }

  if (!session_key_name) {
    ERRLOG(ERR_MSG_NO_SESSION_KEY_NAME);
    return HTTP_INTERNAL_SERVER_ERROR;
  }

  if (!redirect_url) {
    ERRLOG(ERR_MSG_NO_REDIRECT_URL);
    return HTTP_INTERNAL_SERVER_ERROR;
  }

  if ((session_key = get_session_key(r, session_key_name)) &&
      session_key_prefix) {
    snprintf(session_key_buf, sizeof(session_key_buf),
             "%s%s", session_key_prefix, session_key);
    session_key = session_key_buf;
  }

  if (session_key &&
      (rc = memc_get_session(memcached_host, 
                             session_key, sizeof(buf), buf))) {
    ;
  }
  else {
    apr_table_set(r->headers_out, "Location", redirect_url);
    return HTTP_MOVED_TEMPORARILY;
  }

  return OK;
}

static void register_hooks(apr_pool_t *p)
{
    ap_hook_access_checker(memc_sess_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

static memc_sess_conf *conf_from_cmd(cmd_parms *cmd)
{
  return ap_get_module_config(cmd->server->module_config, &memc_sess_module);
}

static const char *cmd_memcached_host(cmd_parms *cmd, void *config,
                                      const char *arg1)
{
  memc_sess_conf *conf = conf_from_cmd(cmd);
  if (!(conf->memcached_host = arg1)) {
    return (const char*)apr_pstrcat(
        cmd->pool, ERR_MSG_NO_MEMCACHED_HOST, arg1, NULL);
  }
  return NULL;
}

static const char *cmd_session_key_name(cmd_parms *cmd, void *config,
                                   const char *arg1)
{
  memc_sess_conf *conf = conf_from_cmd(cmd);
  if (!(conf->session_key_name = arg1)) {
    return (const char*)apr_pstrcat(
        cmd->pool, ERR_MSG_NO_SESSION_KEY_NAME, arg1, NULL);
  }
  return NULL;
}

static const char *cmd_session_key_prefix(cmd_parms *cmd, void *config,
                                   const char *arg1)
{
  memc_sess_conf *conf = conf_from_cmd(cmd);
  if (!(conf->session_key_prefix = arg1)) {
    return (const char*)apr_pstrcat(
        cmd->pool, ERR_MSG_NO_SESSION_KEY_PREFIX, arg1, NULL);
  }
  return NULL;
}

static const char *cmd_redirect_url(cmd_parms *cmd, void *config,
                                   const char *arg1)
{
  memc_sess_conf *conf = conf_from_cmd(cmd);
  if (!(conf->redirect_url = arg1)) {
    return (const char*)apr_pstrcat(
        cmd->pool, ERR_MSG_NO_REDIRECT_URL, arg1, NULL);
  }
  return NULL;
}

static const command_rec memc_sess_cmds[] =
{
  AP_INIT_TAKE1("MemcachedHost", cmd_memcached_host, NULL, ACCESS_CONF,
                "specify host and port of a memcached"),
  AP_INIT_TAKE1("SessionKeyName", cmd_session_key_name, NULL, ACCESS_CONF,
                "specify a session key name"),
  AP_INIT_TAKE1("SessionKeyPrefix", cmd_session_key_prefix, NULL, ACCESS_CONF,
                "specify a session key prefix"),
  AP_INIT_TAKE1("RedirectURL", cmd_redirect_url, NULL, ACCESS_CONF,
                "specify a redirect url"),
  { NULL }
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA memc_sess_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    create_memc_sess_conf, /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    memc_sess_cmds,        /* table of config file commands       */
    register_hooks         /* register hooks                      */
};

